# Generated by Django 5.0.7 on 2024-08-07 08:11

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college_app', '0003_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=70)),
                ('event_venue', models.TextField(default='College Campus')),
                ('event_organizer', models.CharField(default='College', max_length=50)),
                ('event_description', models.TextField()),
                ('event_date', models.DateField(default=django.utils.timezone.now)),
                ('event_pic', models.ImageField(default=' ', upload_to='college_app/event_images')),
            ],
        ),
    ]
