# Generated by Django 5.0.7 on 2024-08-09 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college_app', '0005_alumni_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='event_pic',
        ),
        migrations.AddField(
            model_name='student',
            name='student_pic',
            field=models.ImageField(default=' ', upload_to='college_app/student_images'),
        ),
    ]
