# Generated by Django 5.0.7 on 2024-08-14 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college_app', '0006_remove_student_event_pic_student_student_pic'),
    ]

    operations = [
        migrations.CreateModel(
            name='consultancy',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=50)),
                ('cname', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('phone', models.CharField(max_length=10)),
                ('work_area', models.TextField()),
                ('address', models.TextField()),
            ],
        ),
    ]
